import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const vulf = localFont({
  src: [
    {
      path: '../../public/fonts/Vulf-Mono/VulfMonoDemo-Italic.otf',
      weight: '400'
    }
  ],
  variable: '--font-vulf'
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vulf.variable} font-sans`}>{children}</body>
    </html>
  );
}
